// SPDX-License-Identifier: GPL-3.0-or-later

use std::collections::BTreeMap;

use geosolve_sketch_intent::{AggregateKind, ComputedFeatureKind, GeometryRecipeKind};
use serde::{Deserialize, Serialize};

use crate::FeatureKind;

/// Closed direct-managed lowering routes owned by the optional adapter.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DirectDeclarationLowering {
    FilletSet,
    Line,
    Polyline,
    Rectangle,
}

/// Closed artifact-template lowering routes owned by the optional adapter.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TemplateDeclarationLowering {
    Line,
    Circle,
    Rectangle,
    Fillet,
    Profile,
    Chain,
}

/// Existing native declaration family which ultimately owns one code family.
/// Composite and host-authored routes remain explicit instead of pretending
/// that they are one ordinary intent node.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum NativeDeclarationContract {
    Geometry(GeometryRecipeKind),
    Aggregate(AggregateKind),
    ComputedFeature(ComputedFeatureKind),
    CompositePolyline,
    HostAuthoredFillet,
}

/// Single adapter-owned declaration catalog used by managed dispatch,
/// artifact admission and runtime lowering.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CodeDeclarationFamilyDescriptor {
    pub family: &'static str,
    pub direct: Option<DirectDeclarationLowering>,
    pub template: Option<TemplateDeclarationLowering>,
    pub native: NativeDeclarationContract,
}

/// Every declaration family executable by the optional code adapter.
pub const CODE_DECLARATION_FAMILIES: [CodeDeclarationFamilyDescriptor; 8] = [
    CodeDeclarationFamilyDescriptor {
        family: "aggregate.chain",
        direct: None,
        template: Some(TemplateDeclarationLowering::Chain),
        native: NativeDeclarationContract::Aggregate(AggregateKind::OpenChain),
    },
    CodeDeclarationFamilyDescriptor {
        family: "aggregate.profile",
        direct: None,
        template: Some(TemplateDeclarationLowering::Profile),
        native: NativeDeclarationContract::Aggregate(AggregateKind::ClosedProfile),
    },
    CodeDeclarationFamilyDescriptor {
        family: "computed.fillet",
        direct: None,
        template: Some(TemplateDeclarationLowering::Fillet),
        native: NativeDeclarationContract::HostAuthoredFillet,
    },
    CodeDeclarationFamilyDescriptor {
        family: "computed.filletSet",
        direct: Some(DirectDeclarationLowering::FilletSet),
        template: None,
        native: NativeDeclarationContract::ComputedFeature(ComputedFeatureKind::FilletSet),
    },
    CodeDeclarationFamilyDescriptor {
        family: "geometry.circle",
        direct: None,
        template: Some(TemplateDeclarationLowering::Circle),
        native: NativeDeclarationContract::Geometry(GeometryRecipeKind::CenterRadiusCircle),
    },
    CodeDeclarationFamilyDescriptor {
        family: "geometry.line",
        direct: Some(DirectDeclarationLowering::Line),
        template: Some(TemplateDeclarationLowering::Line),
        native: NativeDeclarationContract::Geometry(GeometryRecipeKind::Segment),
    },
    CodeDeclarationFamilyDescriptor {
        family: "geometry.polyline",
        direct: Some(DirectDeclarationLowering::Polyline),
        template: None,
        native: NativeDeclarationContract::CompositePolyline,
    },
    CodeDeclarationFamilyDescriptor {
        family: "geometry.rectangle",
        direct: Some(DirectDeclarationLowering::Rectangle),
        template: Some(TemplateDeclarationLowering::Rectangle),
        native: NativeDeclarationContract::Geometry(GeometryRecipeKind::TwoPointAlignedRectangle),
    },
];

/// Looks up one executable code declaration family.
#[must_use]
pub fn code_declaration_family(family: &str) -> Option<&'static CodeDeclarationFamilyDescriptor> {
    CODE_DECLARATION_FAMILIES
        .iter()
        .find(|descriptor| descriptor.family == family)
}

/// Descriptor-owned result shape shared by the Rust expansion layer and the
/// generated TypeScript semantic-reference surface.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(tag = "shape", rename_all = "snake_case", deny_unknown_fields)]
pub enum CodeResultShape {
    Leaf {
        kind: FeatureKind,
    },
    Object {
        fields: BTreeMap<String, CodeResultShape>,
    },
    Keyed {
        kind: FeatureKind,
        derived_from_owner: bool,
    },
}

/// One high-level declaration result exposed to managed/custom TypeScript.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CodeDeclarationResultDescriptor {
    pub feature_kind: FeatureKind,
    pub outputs: CodeResultShape,
}

/// Complete code-facing high-level result catalog.
///
/// This deliberately describes semantic result paths, not intent ports or
/// native IDs. The TypeScript source checked into the optional package is
/// generated byte-for-byte from this function and then mapped to branded
/// `OutputRef` values by its type system.
#[must_use]
pub fn declaration_result_catalog() -> BTreeMap<String, CodeDeclarationResultDescriptor> {
    BTreeMap::from([
        (
            "computed.fillet".into(),
            descriptor(object([("arc", leaf(FeatureKind::CurveSpan))])),
        ),
        ("computed.filletSet".into(), descriptor(object([]))),
        (
            "geometry.circle".into(),
            descriptor(object([
                ("center", leaf(FeatureKind::Point)),
                ("circle", leaf(FeatureKind::Curve)),
            ])),
        ),
        (
            "geometry.line".into(),
            descriptor(object([
                ("end", leaf(FeatureKind::Point)),
                ("span", leaf(FeatureKind::CurveSpan)),
                ("start", leaf(FeatureKind::Point)),
            ])),
        ),
        (
            "geometry.polyline".into(),
            descriptor(object([
                ("filletableCorners", keyed(FeatureKind::FeatureCorner, true)),
                ("segments", keyed(FeatureKind::CurveSpan, false)),
                ("vertices", keyed(FeatureKind::Point, false)),
            ])),
        ),
        (
            "geometry.rectangle".into(),
            descriptor(object([
                (
                    "corners",
                    object([
                        ("lowerLeft", leaf(FeatureKind::FeatureCorner)),
                        ("lowerRight", leaf(FeatureKind::FeatureCorner)),
                        ("upperLeft", leaf(FeatureKind::FeatureCorner)),
                        ("upperRight", leaf(FeatureKind::FeatureCorner)),
                    ]),
                ),
                (
                    "edges",
                    object([
                        ("bottom", leaf(FeatureKind::CurveSpan)),
                        ("left", leaf(FeatureKind::CurveSpan)),
                        ("right", leaf(FeatureKind::CurveSpan)),
                        ("top", leaf(FeatureKind::CurveSpan)),
                    ]),
                ),
                ("profile", leaf(FeatureKind::Profile)),
            ])),
        ),
        (
            "geometry.rounded_rectangle".into(),
            descriptor(object([
                (
                    "mounts",
                    object([
                        ("ne", leaf(FeatureKind::Point)),
                        ("nw", leaf(FeatureKind::Point)),
                        ("se", leaf(FeatureKind::Point)),
                        ("sw", leaf(FeatureKind::Point)),
                    ]),
                ),
                ("profile", leaf(FeatureKind::Profile)),
            ])),
        ),
    ])
}

/// Exact checked-in TypeScript catalog source.
///
/// # Panics
///
/// Panics only if the closed descriptor catalog cannot be serialized.
#[must_use]
pub fn typescript_declaration_result_catalog() -> String {
    let json = serde_json::to_string_pretty(&declaration_result_catalog())
        .expect("closed declaration result catalog is serializable");
    format!(
        concat!(
            "// SPDX-License-Identifier: GPL-3.0-or-later\n",
            "// @generated by geosolve-sketch-code::typescript_declaration_result_catalog.\n",
            "// Do not edit by hand.\n\n",
            "export const DECLARATION_RESULT_CATALOG = {} as const;\n",
        ),
        json,
    )
}

fn descriptor(outputs: CodeResultShape) -> CodeDeclarationResultDescriptor {
    CodeDeclarationResultDescriptor {
        feature_kind: FeatureKind::Feature,
        outputs,
    }
}

fn leaf(kind: FeatureKind) -> CodeResultShape {
    CodeResultShape::Leaf { kind }
}

fn keyed(kind: FeatureKind, derived_from_owner: bool) -> CodeResultShape {
    CodeResultShape::Keyed {
        kind,
        derived_from_owner,
    }
}

fn object<const N: usize>(fields: [(&'static str, CodeResultShape); N]) -> CodeResultShape {
    CodeResultShape::Object {
        fields: fields
            .into_iter()
            .map(|(name, value)| (name.to_owned(), value))
            .collect(),
    }
}
