// SPDX-License-Identifier: GPL-3.0-or-later

//! Generate wire and toolbar projections directly from the native tool owners.

use geosolve_constraint_editor::{AuthoringTool, GeometryToolVariant, ModifyTool};
use std::{env, fmt::Write as _, fs, path::PathBuf, process::ExitCode};

fn write_mapping<'a>(
    output: &mut String,
    name: &str,
    keys: impl Iterator<Item = (&'a str, String)>,
) {
    writeln!(output, "export const {name} = {{").expect("String write");
    for (key, command) in keys {
        writeln!(output, "  \"{key}\": \"{command}\",").expect("String write");
    }
    writeln!(output, "}} as const;\n").expect("String write");
}

fn generated() -> String {
    let mut output = String::from(
        "// SPDX-License-Identifier: GPL-3.0-or-later\n// @generated by geosolve-constraint-editor/examples/generate_tool_catalog.rs. Do not edit.\n\n",
    );
    write_mapping(
        &mut output,
        "constructionTools",
        GeometryToolVariant::ALL
            .into_iter()
            .map(|tool| (tool.key(), tool.key().replace('-', "_"))),
    );
    write_mapping(
        &mut output,
        "operationTools",
        AuthoringTool::ALL
            .into_iter()
            .map(|tool| (tool.key(), tool.key().replace('-', "_")))
            .chain(
                ModifyTool::PALETTE
                    .into_iter()
                    .map(|tool| (tool.key(), tool.command_key())),
            ),
    );
    write_mapping(
        &mut output,
        "auxiliaryTools",
        ModifyTool::ALL
            .into_iter()
            .filter(|tool| !ModifyTool::PALETTE.contains(tool))
            .map(|tool| (tool.key(), tool.command_key())),
    );
    output.push_str("export type ConstructionTool = (typeof constructionTools)[keyof typeof constructionTools];\nexport type ToolOperationTool = (typeof operationTools)[keyof typeof operationTools] | (typeof auxiliaryTools)[keyof typeof auxiliaryTools];\n");
    output
}

fn main() -> ExitCode {
    let mut arguments = env::args_os().skip(1);
    let (Some(mode), Some(path)) = (arguments.next(), arguments.next()) else {
        eprintln!("usage: generate_tool_catalog (--check|--write) <tool-catalog.ts>");
        return ExitCode::FAILURE;
    };
    if arguments.next().is_some() {
        eprintln!("unexpected extra argument");
        return ExitCode::FAILURE;
    }
    let path = PathBuf::from(path);
    let expected = generated();
    let result = if mode == "--write" {
        fs::write(&path, expected)
    } else if mode == "--check" {
        fs::read_to_string(&path).and_then(|actual| {
            if actual == expected {
                Ok(())
            } else {
                Err(std::io::Error::other(
                    "tool catalog differs from native authoring owners; run generate:tools",
                ))
            }
        })
    } else {
        eprintln!("expected --check or --write");
        return ExitCode::FAILURE;
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("{}: {error}", path.display());
            ExitCode::FAILURE
        }
    }
}
