// SPDX-License-Identifier: GPL-3.0-or-later
//! Durable server order, identity and duplicate handling around domain workers.
//!
//! The ledger records accepted *input identities*, not solved geometry. Only the
//! host's independently validated domain session may produce a completion. Client
//! commands never deserialize into a prepared operation or call `complete`.

use std::collections::{BTreeMap, VecDeque};

use sha2::{Digest, Sha256};
use thiserror::Error;

use crate::protocol::{
    Command, Connection, DocumentEvent, JournalRecord, Limits, MAX_REVISION, OperationId, Outcome,
    PROTOCOL_VERSION, Principal, Receipt, Resume, Role, Submit,
};

#[derive(Debug, Error, Eq, PartialEq)]
pub enum AuthorityError {
    #[error("invalid protocol value: {0}")]
    Invalid(String),
    #[error("connection is stale or not authenticated")]
    Connection,
    #[error("this session cannot edit")]
    ReadOnly,
    #[error("operation ID already names different immutable intent")]
    DuplicateMismatch,
    #[error("resource limit: {0}; retain pending work and resume later")]
    Backpressure(String),
    #[error("prepared operation no longer owns the exact accepted input")]
    StalePrepared,
    #[error("persistence failed; recover the journal before accepting more work: {0}")]
    Durability(String),
    #[error("journal is corrupt: {0}")]
    Corrupt(String),
}

#[derive(Clone, Debug)]
struct Entry {
    receipt: Receipt,
    command: Command,
    digest: String,
}

/// Opaque worker ticket issued in server admission order. It is deliberately not
/// serializable/deserializable and cannot be constructed from a detached scene.
#[derive(Clone, Debug)]
pub struct PreparedOperation {
    document_id: String,
    document_epoch: String,
    operation: OperationId,
    admission: u64,
    command: Command,
    accepted_revision: u64,
    accepted_input: String,
    server_epoch: String,
}

impl PreparedOperation {
    pub fn operation(&self) -> &OperationId {
        &self.operation
    }
    pub fn command(&self) -> &Command {
        &self.command
    }
    pub fn accepted_revision(&self) -> u64 {
        self.accepted_revision
    }
    pub fn accepted_input(&self) -> &str {
        &self.accepted_input
    }
}

/// Trusted host result after independent domain validation. This is not a wire
/// request and contains no client-supplied residual acceptance switch.
#[derive(Clone, Debug)]
pub enum Completion {
    Accepted {
        accepted_input: String,
        summary: String,
    },
    Rejected {
        code: String,
        message: String,
    },
}

#[derive(Clone, Debug)]
pub struct DocumentAuthority {
    document_id: String,
    document_epoch: String,
    server_epoch: String,
    limits: Limits,
    sessions: BTreeMap<String, Connection>,
    entries: BTreeMap<OperationId, Entry>,
    pending: VecDeque<OperationId>,
    active: Option<PreparedOperation>,
    records: Vec<JournalRecord>,
    ledger_bytes: usize,
    accepted_revision: u64,
    accepted_input: String,
    poisoned: bool,
}

impl DocumentAuthority {
    /// The host supplies durable document identity and a fresh process epoch.
    /// `accepted_input` identifies independently reconstructed initial source/design.
    ///
    /// # Errors
    /// Rejects malformed identities and unusable resource limits.
    pub fn new(
        document_id: String,
        document_epoch: String,
        server_epoch: String,
        accepted_input: String,
        limits: Limits,
    ) -> Result<Self, AuthorityError> {
        for id in [
            &document_id,
            &document_epoch,
            &server_epoch,
            &accepted_input,
        ] {
            validate_id(id)?;
        }
        if limits.max_sessions == 0
            || limits.max_pending == 0
            || limits.max_pending_per_client == 0
            || limits.max_operations == 0
            || limits.max_command_bytes == 0
            || limits.max_ledger_bytes == 0
            || limits.max_resume_records == 0
        {
            return Err(AuthorityError::Invalid("limits must be nonzero".into()));
        }
        Ok(Self {
            document_id,
            document_epoch,
            server_epoch,
            limits,
            sessions: BTreeMap::new(),
            entries: BTreeMap::new(),
            pending: VecDeque::new(),
            active: None,
            records: Vec::new(),
            ledger_bytes: 0,
            accepted_revision: 0,
            accepted_input,
            poisoned: false,
        })
    }

    /// Join is a trusted host API: authenticate the user and role before calling.
    /// Session IDs must be fresh unguessable values generated by the host.
    /// Reconnecting one client invalidates its previous connection, not its work.
    ///
    /// # Errors
    /// Rejects invalid/reused session identities and session exhaustion.
    pub fn connect(
        &mut self,
        principal: Principal,
        client_id: String,
        session_id: String,
    ) -> Result<Connection, AuthorityError> {
        for id in [&principal.user_id, &client_id, &session_id] {
            validate_id(id)?;
        }
        if self.sessions.contains_key(&session_id) {
            return Err(AuthorityError::Invalid("session ID must be fresh".into()));
        }
        let previous = self
            .sessions
            .values()
            .find(|connection| {
                connection.client_id == client_id && connection.user_id == principal.user_id
            })
            .map(|connection| connection.session_id.clone());
        if previous.is_none() && self.sessions.len() >= self.limits.max_sessions {
            return Err(AuthorityError::Backpressure("sessions".into()));
        }
        if let Some(previous) = previous {
            self.sessions.remove(&previous);
        }
        let connection = Connection {
            protocol: PROTOCOL_VERSION,
            document_id: self.document_id.clone(),
            document_epoch: self.document_epoch.clone(),
            server_epoch: self.server_epoch.clone(),
            session_id: session_id.clone(),
            client_id,
            user_id: principal.user_id,
            role: principal.role,
        };
        self.sessions.insert(session_id, connection.clone());
        Ok(connection)
    }

    pub fn disconnect(&mut self, session_id: &str) {
        self.sessions.remove(session_id);
    }
    pub fn accepted_revision(&self) -> u64 {
        self.accepted_revision
    }
    pub fn accepted_input(&self) -> &str {
        &self.accepted_input
    }
    pub fn latest_sequence(&self) -> u64 {
        self.records.last().map_or(0, |record| record.sequence)
    }
    pub fn pending_count(&self) -> usize {
        self.pending.len()
    }
    pub fn ledger_bytes(&self) -> usize {
        self.ledger_bytes
    }
    pub fn needs_recovery(&self) -> bool {
        self.poisoned
    }

    /// Persist admission before acknowledging even queued work. Duplicate lookup
    /// precedes basis/queue checks so a lost ACK remains recoverable after progress.
    /// The persistence callback must append atomically/recoverably and sync durability.
    ///
    /// # Errors
    /// Rejects forged/stale connections, viewer edits, changed duplicate intent,
    /// invalid future bases, exhausted resources or uncertain durability.
    pub fn admit(
        &mut self,
        request: &Submit,
        persist: impl FnOnce(&JournalRecord) -> Result<(), String>,
    ) -> Result<Receipt, AuthorityError> {
        self.require_healthy()?;
        self.authenticate(&request.connection)?;
        if request.connection.role != Role::Editor {
            return Err(AuthorityError::ReadOnly);
        }
        validate_id(&request.request_id)?;
        let operation = OperationId {
            user_id: request.connection.user_id.clone(),
            client_id: request.connection.client_id.clone(),
            request_id: request.request_id.clone(),
        };
        let bytes = json_bytes(&request.command)?;
        if bytes.len() > self.limits.max_command_bytes {
            return Err(AuthorityError::Backpressure("command bytes".into()));
        }
        let digest = digest(&bytes);
        if let Some(entry) = self.entries.get(&operation) {
            return if entry.digest == digest {
                Ok(entry.receipt.clone())
            } else {
                Err(AuthorityError::DuplicateMismatch)
            };
        }
        if request.command.basis_revision > self.accepted_revision {
            return Err(AuthorityError::Invalid(
                "basis is ahead of accepted revision".into(),
            ));
        }
        self.check_admission_capacity(&operation)?;
        let admission = next(
            self.entries
                .len()
                .try_into()
                .map_err(|_| AuthorityError::Backpressure("operation counter".into()))?,
        )?;
        let event = DocumentEvent::Admitted {
            operation: operation.clone(),
            admission,
            command: request.command.clone(),
            digest,
        };
        self.persist_event(event, persist)?;
        Ok(self.entries[&operation].receipt.clone())
    }

    /// Gives only the oldest unfinished operation to a domain worker. Text and
    /// read paths can continue while this opaque ticket is being evaluated.
    ///
    /// # Errors
    /// Refuses uncertain durability until journal recovery.
    pub fn begin_next(&mut self) -> Result<Option<PreparedOperation>, AuthorityError> {
        self.require_healthy()?;
        if self.active.is_some() {
            return Ok(None);
        }
        let Some(operation) = self.pending.front() else {
            return Ok(None);
        };
        let entry = &self.entries[operation];
        let prepared = PreparedOperation {
            document_id: self.document_id.clone(),
            document_epoch: self.document_epoch.clone(),
            operation: operation.clone(),
            admission: entry.receipt.admission,
            command: entry.command.clone(),
            accepted_revision: self.accepted_revision,
            accepted_input: self.accepted_input.clone(),
            server_epoch: self.server_epoch.clone(),
        };
        self.active = Some(prepared.clone());
        Ok(Some(prepared))
    }

    /// Records the trusted worker's result after exact-input validation. Persist
    /// before exposing acceptance; a failed or ambiguous write poisons authoring.
    ///
    /// # Errors
    /// Rejects stale/cross-process/out-of-order tickets, malformed results or
    /// uncertain durability without advancing the visible accepted revision.
    pub fn complete(
        &mut self,
        prepared: &PreparedOperation,
        completion: Completion,
        persist: impl FnOnce(&JournalRecord) -> Result<(), String>,
    ) -> Result<Receipt, AuthorityError> {
        self.require_healthy()?;
        let active = self.active.as_ref().ok_or(AuthorityError::StalePrepared)?;
        if prepared.document_id != self.document_id
            || prepared.document_epoch != self.document_epoch
            || prepared.operation != active.operation
            || prepared.admission != active.admission
            || prepared.server_epoch != self.server_epoch
            || prepared.accepted_revision != self.accepted_revision
            || prepared.accepted_input != self.accepted_input
            || prepared.command != active.command
        {
            return Err(AuthorityError::StalePrepared);
        }
        let outcome = match completion {
            Completion::Accepted {
                accepted_input,
                summary,
            } => {
                validate_id(&accepted_input)?;
                validate_message(&summary)?;
                Outcome::Accepted {
                    revision: next(self.accepted_revision)?,
                    accepted_input,
                    summary,
                }
            }
            Completion::Rejected { code, message } => {
                validate_id(&code)?;
                validate_message(&message)?;
                Outcome::Rejected { code, message }
            }
        };
        self.persist_event(
            DocumentEvent::Finished {
                operation: prepared.operation.clone(),
                outcome,
            },
            persist,
        )?;
        self.active = None;
        Ok(self.entries[&prepared.operation].receipt.clone())
    }

    /// Resolve one's own admitted operation without depending on scene refresh.
    ///
    /// # Errors
    /// Rejects stale or forged connections and malformed request IDs.
    pub fn receipt(
        &self,
        connection: &Connection,
        request_id: &str,
    ) -> Result<Option<Receipt>, AuthorityError> {
        self.authenticate(connection)?;
        validate_id(request_id)?;
        let operation = OperationId {
            user_id: connection.user_id.clone(),
            client_id: connection.client_id.clone(),
            request_id: request_id.into(),
        };
        Ok(self
            .entries
            .get(&operation)
            .map(|entry| entry.receipt.clone()))
    }

    /// Returns bounded durable event pages, independent from presence buffering.
    ///
    /// # Errors
    /// Rejects forged connections or a cursor ahead of the durable journal.
    pub fn resume(&self, connection: &Connection, after: u64) -> Result<Resume, AuthorityError> {
        self.authenticate(connection)?;
        if after > self.latest_sequence() {
            return Err(AuthorityError::Invalid("resume cursor is ahead".into()));
        }
        Ok(Resume::Events {
            records: self
                .records
                .iter()
                .filter(|record| record.sequence > after)
                .take(self.limits.max_resume_records)
                .cloned()
                .collect(),
        })
    }

    /// Reconstructs only the ordered input ledger. The host must independently
    /// rebuild/validate the final accepted geometry before serving model edits.
    ///
    /// # Errors
    /// Rejects corrupt, reordered, foreign, over-limit or semantically inconsistent
    /// records. An interrupted admission is queued again under the new server epoch.
    pub fn restore(
        document_id: String,
        document_epoch: String,
        server_epoch: String,
        initial_input: String,
        limits: Limits,
        records: &[JournalRecord],
    ) -> Result<Self, AuthorityError> {
        let mut state = Self::new(
            document_id,
            document_epoch,
            server_epoch,
            initial_input,
            limits,
        )?;
        for record in records {
            let expected = state.record(record.event.clone())?;
            if &expected != record {
                return Err(AuthorityError::Corrupt(
                    "record chain or document identity".into(),
                ));
            }
            state.validate_event(&record.event)?;
            let size = json_bytes(record)?.len();
            state.check_record_capacity(size, &record.event)?;
            state.apply_record(record.clone(), size);
        }
        Ok(state)
    }

    fn authenticate(&self, connection: &Connection) -> Result<(), AuthorityError> {
        if self.sessions.get(&connection.session_id) != Some(connection) {
            return Err(AuthorityError::Connection);
        }
        Ok(())
    }
    fn require_healthy(&self) -> Result<(), AuthorityError> {
        if self.poisoned {
            return Err(AuthorityError::Durability(
                "previous append outcome is uncertain".into(),
            ));
        }
        Ok(())
    }
    fn check_admission_capacity(&self, operation: &OperationId) -> Result<(), AuthorityError> {
        if self.entries.len() >= self.limits.max_operations {
            return Err(AuthorityError::Backpressure("operation ledger".into()));
        }
        if self.pending.len() >= self.limits.max_pending {
            return Err(AuthorityError::Backpressure("pending operations".into()));
        }
        let count = self
            .pending
            .iter()
            .filter(|id| id.user_id == operation.user_id && id.client_id == operation.client_id)
            .count();
        if count >= self.limits.max_pending_per_client {
            return Err(AuthorityError::Backpressure(
                "client pending operations".into(),
            ));
        }
        Ok(())
    }
    fn record(&self, event: DocumentEvent) -> Result<JournalRecord, AuthorityError> {
        let mut record = JournalRecord {
            protocol: PROTOCOL_VERSION,
            document_id: self.document_id.clone(),
            document_epoch: self.document_epoch.clone(),
            sequence: next(self.latest_sequence())?,
            accepted_revision: self.accepted_revision,
            accepted_input: self.accepted_input.clone(),
            previous_digest: self
                .records
                .last()
                .map_or_else(String::new, |record| record.digest.clone()),
            event,
            digest: String::new(),
        };
        record.digest = digest(&json_bytes(&record)?);
        Ok(record)
    }
    fn check_record_capacity(
        &self,
        size: usize,
        event: &DocumentEvent,
    ) -> Result<(), AuthorityError> {
        // Reserve room for one bounded terminal result for every admitted operation.
        // A full ledger must still be able to finish all acknowledged work.
        let pending_after = match event {
            DocumentEvent::Admitted { .. } => self.pending.len() + 1,
            DocumentEvent::Finished { .. } => self.pending.len().saturating_sub(1),
        };
        let reserved = pending_after.saturating_mul(8192);
        if self
            .ledger_bytes
            .saturating_add(size)
            .saturating_add(reserved)
            > self.limits.max_ledger_bytes
        {
            return Err(AuthorityError::Backpressure("durable ledger bytes".into()));
        }
        Ok(())
    }
    fn persist_event(
        &mut self,
        event: DocumentEvent,
        persist: impl FnOnce(&JournalRecord) -> Result<(), String>,
    ) -> Result<(), AuthorityError> {
        self.validate_event(&event)?;
        let record = self.record(event)?;
        let size = json_bytes(&record)?.len();
        self.check_record_capacity(size, &record.event)?;
        if let Err(error) = persist(&record) {
            self.poisoned = true;
            return Err(AuthorityError::Durability(error));
        }
        self.apply_record(record, size);
        Ok(())
    }
    fn validate_event(&self, event: &DocumentEvent) -> Result<(), AuthorityError> {
        let corrupt = |reason: &str| AuthorityError::Corrupt(reason.into());
        match event {
            DocumentEvent::Admitted {
                operation,
                admission,
                command,
                digest: expected,
            } => {
                for id in [
                    &operation.user_id,
                    &operation.client_id,
                    &operation.request_id,
                ] {
                    validate_id(id)?;
                }
                if self.entries.contains_key(operation)
                    || *admission != self.entries.len() as u64 + 1
                    || command.basis_revision > self.accepted_revision
                {
                    return Err(corrupt("invalid admission order/basis"));
                }
                let bytes = json_bytes(command)?;
                if bytes.len() > self.limits.max_command_bytes || digest(&bytes) != *expected {
                    return Err(corrupt("command size/digest"));
                }
                self.check_admission_capacity(operation)?;
            }
            DocumentEvent::Finished { operation, outcome } => {
                if self.pending.front() != Some(operation) {
                    return Err(corrupt("out-of-order terminal event"));
                }
                match outcome {
                    Outcome::Accepted {
                        revision,
                        accepted_input,
                        summary,
                    } => {
                        if *revision != next(self.accepted_revision)? {
                            return Err(corrupt("accepted revision"));
                        }
                        validate_id(accepted_input)?;
                        validate_message(summary)?;
                    }
                    Outcome::Rejected { code, message } => {
                        validate_id(code)?;
                        validate_message(message)?;
                    }
                }
            }
        }
        Ok(())
    }
    fn apply_record(&mut self, record: JournalRecord, size: usize) {
        match &record.event {
            DocumentEvent::Admitted {
                operation,
                admission,
                command,
                digest,
            } => {
                self.entries.insert(
                    operation.clone(),
                    Entry {
                        receipt: Receipt {
                            operation: operation.clone(),
                            admission: *admission,
                            outcome: None,
                        },
                        command: command.clone(),
                        digest: digest.clone(),
                    },
                );
                self.pending.push_back(operation.clone());
            }
            DocumentEvent::Finished { operation, outcome } => {
                self.entries
                    .get_mut(operation)
                    .expect("validated pending operation")
                    .receipt
                    .outcome = Some(outcome.clone());
                self.pending.pop_front();
                if let Outcome::Accepted {
                    revision,
                    accepted_input,
                    ..
                } = outcome
                {
                    self.accepted_revision = *revision;
                    self.accepted_input.clone_from(accepted_input);
                }
            }
        }
        self.ledger_bytes += size;
        self.records.push(record);
    }
}

fn validate_id(id: &str) -> Result<(), AuthorityError> {
    if id.is_empty()
        || id.len() > 128
        || !id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || b"_-.:".contains(&byte))
    {
        return Err(AuthorityError::Invalid(
            "identity must be 1–128 ASCII identifier characters".into(),
        ));
    }
    Ok(())
}
fn validate_message(message: &str) -> Result<(), AuthorityError> {
    if message.len() > 1024 {
        return Err(AuthorityError::Invalid(
            "outcome message exceeds 1024 bytes".into(),
        ));
    }
    Ok(())
}
fn next(value: u64) -> Result<u64, AuthorityError> {
    value
        .checked_add(1)
        .filter(|next| *next <= MAX_REVISION)
        .ok_or_else(|| AuthorityError::Backpressure("exact revision counter".into()))
}
fn json_bytes(value: &impl serde::Serialize) -> Result<Vec<u8>, AuthorityError> {
    serde_json::to_vec(value).map_err(|error| AuthorityError::Invalid(error.to_string()))
}
fn digest(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}
