// SPDX-License-Identifier: GPL-3.0-or-later
// @generated by geosolve-constraint-editor/examples/generate_tool_catalog.rs. Do not edit.

export const constructionTools = {
  "sketch-point": "sketch_point",
  "segment": "segment",
  "polyline": "polyline",
  "midpoint-line": "midpoint_line",
  "two-point-aligned-rectangle": "two_point_aligned_rectangle",
  "three-point-corner-rectangle": "three_point_corner_rectangle",
  "center-rectangle": "center_rectangle",
  "three-point-center-rectangle": "three_point_center_rectangle",
  "center-radius-circle": "center_radius_circle",
  "two-point-diameter-circle": "two_point_diameter_circle",
  "three-point-circle": "three_point_circle",
  "center-arc": "center_arc",
  "three-point-arc": "three_point_arc",
  "tangent-arc": "tangent_arc",
  "center-axes-ellipse": "center_axes_ellipse",
  "axis-endpoints-ellipse": "axis_endpoints_ellipse",
  "center-axes-elliptical-arc": "center_axes_elliptical_arc",
  "axis-endpoints-elliptical-arc": "axis_endpoints_elliptical_arc",
  "quadratic-bezier": "quadratic_bezier",
  "cubic-bezier": "cubic_bezier",
  "rational-quadratic-conic": "rational_quadratic_conic",
  "parabola": "parabola",
  "hyperbola": "hyperbola",
  "open-control-nurbs": "open_control_nurbs",
  "periodic-control-nurbs": "periodic_control_nurbs",
} as const;

export const operationTools = {
  "lock": "lock",
  "coincident": "coincident",
  "horizontal": "horizontal",
  "vertical": "vertical",
  "concentric": "concentric",
  "collinear": "collinear",
  "parallel": "parallel",
  "perpendicular": "perpendicular",
  "equal": "equal",
  "midpoint": "midpoint",
  "symmetric": "symmetric",
  "tangent": "tangent",
  "continuity": "continuity",
  "point-distance": "point_distance",
  "segment-length": "segment_length",
  "radius": "radius",
  "diameter": "diameter",
  "oriented-angle": "oriented_angle",
  "fillet": "fillet",
  "offset": "offset",
} as const;

export const auxiliaryTools = {
  "geometry-role": "toggle_geometry_role",
} as const;

export type ConstructionTool = (typeof constructionTools)[keyof typeof constructionTools];
export type ToolOperationTool = (typeof operationTools)[keyof typeof operationTools] | (typeof auxiliaryTools)[keyof typeof auxiliaryTools];
