// SPDX-License-Identifier: GPL-3.0-or-later

use std::collections::{BTreeMap, BTreeSet};

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::ids::{
    ChildId, ComponentIdentity, ContentDigest, NodeId, PortId, ReservationId, Revision,
    digest_bytes,
};
use crate::model::{
    BootstrapNativeKind, InputRole, InputSlot, IntentChildSchema, IntentFieldKey,
    IntentGraphIdentity, IntentIdentityFlow, IntentInstanceState, IntentLiteral,
    IntentNativeReservationKind, IntentNodeDraft, IntentNodeKind, IntentOperationOutput,
    IntentOperationOutputKind, IntentPortKind, IntentPortRef, IntentPortSelector,
    IntentReservationLedgerIdentity, LeafField, LeafRef, MAX_INTENT_NODE_FIELDS,
    MAX_INTENT_NODE_INPUTS, MAX_INTENT_OPERATION_OUTPUTS, PatchPortRef, PortSpec,
    checked_child_count, child_port_specs, literal_matches_leaf, node_port_specs,
};

/// Strict canonical graph wire version.
pub const INTENT_GRAPH_VERSION: u32 = 1;
/// Maximum canonical graph JSON accepted by this crate.
pub const MAX_INTENT_GRAPH_JSON_BYTES: usize = 64 * 1024 * 1024;
/// Maximum declarations retained in one graph.
pub const MAX_INTENT_NODES: usize = 65_536;
/// Maximum never-reused native reservations retained by one session.
pub const MAX_INTENT_RESERVATION_LEDGER_ENTRIES: usize = 1_048_576;

/// Monotonic stable-ID cursors. History restore never lowers these values.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct IntentAllocatorHighWater {
    pub next_node: NodeId,
    pub next_port: PortId,
    pub next_reservation: ReservationId,
    pub next_child: ChildId,
    pub next_cell: crate::CellId,
}

impl IntentAllocatorHighWater {
    #[must_use]
    pub const fn initial() -> Self {
        Self {
            next_node: NodeId::from_raw(1),
            next_port: PortId::from_raw(1),
            next_reservation: ReservationId::from_raw(1),
            next_child: ChildId::from_raw(1),
            // Cell 1 is the built-in Sketch cell.
            next_cell: crate::CellId::from_raw(2),
        }
    }

    pub(crate) fn allocate_node(&mut self) -> Result<NodeId, IntentGraphError> {
        let value = self.next_node;
        self.next_node = NodeId::from_raw(
            value
                .raw()
                .checked_add(1)
                .ok_or(IntentGraphError::IdExhausted("node"))?,
        );
        Ok(value)
    }

    pub(crate) fn allocate_port(&mut self) -> Result<PortId, IntentGraphError> {
        let value = self.next_port;
        self.next_port = PortId::from_raw(
            value
                .raw()
                .checked_add(1)
                .ok_or(IntentGraphError::IdExhausted("port"))?,
        );
        Ok(value)
    }

    pub(crate) fn allocate_reservation(&mut self) -> Result<ReservationId, IntentGraphError> {
        let value = self.next_reservation;
        self.next_reservation = ReservationId::from_raw(
            value
                .raw()
                .checked_add(1)
                .ok_or(IntentGraphError::IdExhausted("reservation"))?,
        );
        Ok(value)
    }

    pub(crate) fn allocate_child(&mut self) -> Result<ChildId, IntentGraphError> {
        let value = self.next_child;
        self.next_child = ChildId::from_raw(
            value
                .raw()
                .checked_add(1)
                .ok_or(IntentGraphError::IdExhausted("child"))?,
        );
        Ok(value)
    }

    pub(crate) fn allocate_cell(&mut self) -> Result<crate::CellId, IntentGraphError> {
        let value = self.next_cell;
        self.next_cell = crate::CellId::from_raw(
            value
                .raw()
                .checked_add(1)
                .ok_or(IntentGraphError::IdExhausted("cell"))?,
        );
        Ok(value)
    }
}

impl Default for IntentAllocatorHighWater {
    fn default() -> Self {
        Self::initial()
    }
}

/// One stable native identity reservation generated by a schema.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct IntentReservation {
    pub id: ReservationId,
    pub kind: IntentNativeReservationKind,
    /// Exact companion for atomic constraint/source or dimension/source
    /// allocation. Other native reservations have no companion.
    pub paired_with: Option<ReservationId>,
}

/// Current declaration disposition of one never-reused reservation record.
/// Tombstoned records may become declared again through Undo, but the record
/// and its identity are never removed or reused.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum IntentReservationState {
    Declared,
    Suppressed,
    Tombstoned,
}

/// Durable typed ownership metadata for one native reservation.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct IntentReservationRecord {
    pub id: ReservationId,
    pub kind: IntentNativeReservationKind,
    pub owner_node: NodeId,
    pub owner_port: PortId,
    pub paired_with: Option<ReservationId>,
    pub state: IntentReservationState,
}

/// Monotonic session-level reservation and tombstone authority.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct IntentReservationLedger {
    pub(crate) revision: Revision,
    entries: BTreeMap<ReservationId, IntentReservationRecord>,
}

impl IntentReservationLedger {
    #[must_use]
    pub fn empty() -> Self {
        Self {
            revision: Revision::from_raw(0),
            entries: BTreeMap::new(),
        }
    }

    #[must_use]
    pub const fn entries(&self) -> &BTreeMap<ReservationId, IntentReservationRecord> {
        &self.entries
    }

    #[must_use]
    pub const fn revision(&self) -> Revision {
        self.revision
    }

    #[must_use]
    /// Returns the exact revisioned identity of all durable records.
    ///
    /// # Panics
    ///
    /// Panics only if serialization of this closed schema fails.
    pub fn identity(&self) -> IntentReservationLedgerIdentity {
        IntentReservationLedgerIdentity(ComponentIdentity {
            revision: self.revision,
            digest: digest_bytes(
                &serde_json::to_vec(&(self.revision, &self.entries))
                    .expect("reservation ledger is infallibly serializable"),
            ),
        })
    }

    pub(crate) fn reconcile(&mut self, graph: &IntentGraph) -> Result<bool, IntentGraphError> {
        let mut changed = false;
        for node in graph.nodes.values() {
            for reservation in node.reservations.values() {
                let owner_port = node
                    .ports
                    .values()
                    .find_map(|port| match port.flow {
                        IntentIdentityFlow::Created {
                            reservation: candidate,
                        } if candidate == reservation.id => Some(port.id),
                        _ => None,
                    })
                    .ok_or(IntentGraphError::UnusedReservation {
                        node: node.id,
                        reservation: reservation.id,
                    })?;
                let record = IntentReservationRecord {
                    id: reservation.id,
                    kind: reservation.kind,
                    owner_node: node.id,
                    owner_port,
                    paired_with: reservation.paired_with,
                    state: if node.suppressed {
                        IntentReservationState::Suppressed
                    } else {
                        IntentReservationState::Declared
                    },
                };
                if let Some(existing) = self.entries.get_mut(&reservation.id) {
                    if (
                        existing.id,
                        existing.kind,
                        existing.owner_node,
                        existing.owner_port,
                        existing.paired_with,
                    ) != (
                        record.id,
                        record.kind,
                        record.owner_node,
                        record.owner_port,
                        record.paired_with,
                    ) {
                        return Err(IntentGraphError::ReservationLedgerMismatch {
                            reservation: reservation.id,
                        });
                    }
                    if existing.state != record.state {
                        existing.state = record.state;
                        changed = true;
                    }
                } else {
                    if self.entries.len() == MAX_INTENT_RESERVATION_LEDGER_ENTRIES {
                        return Err(IntentGraphError::ResourceLimit {
                            resource: "reservation ledger entries",
                            actual: self.entries.len() + 1,
                            limit: MAX_INTENT_RESERVATION_LEDGER_ENTRIES,
                        });
                    }
                    self.entries.insert(reservation.id, record);
                    changed = true;
                }
            }
        }
        for record in self.entries.values_mut() {
            if graph
                .nodes
                .get(&record.owner_node)
                .and_then(|node| node.reservations.get(&record.id))
                .is_none()
                && record.state != IntentReservationState::Tombstoned
            {
                record.state = IntentReservationState::Tombstoned;
                changed = true;
            }
        }
        self.validate_against_graph(graph)?;
        Ok(changed)
    }

    pub(crate) fn validate_against_graph(
        &self,
        graph: &IntentGraph,
    ) -> Result<(), IntentGraphError> {
        self.validate()?;
        self.validate_graph_metadata(graph)?;
        for node in graph.nodes.values() {
            for reservation in node.reservations.values() {
                let record = &self.entries[&reservation.id];
                let expected_state = if node.suppressed {
                    IntentReservationState::Suppressed
                } else {
                    IntentReservationState::Declared
                };
                if record.state != expected_state {
                    return Err(IntentGraphError::ReservationLedgerMismatch {
                        reservation: reservation.id,
                    });
                }
            }
        }
        for record in self.entries.values() {
            let exists = graph
                .nodes
                .get(&record.owner_node)
                .is_some_and(|node| node.reservations.contains_key(&record.id));
            if exists == (record.state == IntentReservationState::Tombstoned) {
                return Err(IntentGraphError::ReservationLedgerMismatch {
                    reservation: record.id,
                });
            }
        }
        Ok(())
    }

    /// Validates durable reservation ownership for any current or historical
    /// graph without requiring its historical disposition to equal the
    /// ledger's current disposition.
    pub(crate) fn validate_graph_metadata(
        &self,
        graph: &IntentGraph,
    ) -> Result<(), IntentGraphError> {
        self.validate()?;
        for node in graph.nodes.values() {
            for reservation in node.reservations.values() {
                let Some(record) = self.entries.get(&reservation.id) else {
                    return Err(IntentGraphError::ReservationLedgerMismatch {
                        reservation: reservation.id,
                    });
                };
                if record.kind != reservation.kind
                    || record.owner_node != node.id
                    || record.paired_with != reservation.paired_with
                    || !node.ports.values().any(|port| {
                        port.id == record.owner_port
                            && port.flow
                                == IntentIdentityFlow::Created {
                                    reservation: reservation.id,
                                }
                    })
                {
                    return Err(IntentGraphError::ReservationLedgerMismatch {
                        reservation: reservation.id,
                    });
                }
            }
        }
        Ok(())
    }

    pub(crate) fn validate_superset_of(&self, historical: &Self) -> Result<(), IntentGraphError> {
        self.validate()?;
        historical.validate()?;
        if historical.revision > self.revision {
            return Err(IntentGraphError::ReservationLedgerRevisionRegression {
                historical: historical.revision,
                current: self.revision,
            });
        }
        for (id, record) in &historical.entries {
            let Some(current) = self.entries.get(id) else {
                return Err(IntentGraphError::ReservationLedgerMismatch { reservation: *id });
            };
            if (
                record.id,
                record.kind,
                record.owner_node,
                record.owner_port,
                record.paired_with,
            ) != (
                current.id,
                current.kind,
                current.owner_node,
                current.owner_port,
                current.paired_with,
            ) {
                return Err(IntentGraphError::ReservationLedgerMismatch { reservation: *id });
            }
        }
        Ok(())
    }

    pub(crate) fn validate(&self) -> Result<(), IntentGraphError> {
        if self.entries.len() > MAX_INTENT_RESERVATION_LEDGER_ENTRIES {
            return Err(IntentGraphError::ResourceLimit {
                resource: "reservation ledger entries",
                actual: self.entries.len(),
                limit: MAX_INTENT_RESERVATION_LEDGER_ENTRIES,
            });
        }
        for (id, record) in &self.entries {
            if *id != record.id {
                return Err(IntentGraphError::MapKeyMismatch {
                    kind: "reservation ledger",
                });
            }
            if let Some(pair) = record.paired_with {
                let Some(companion) = self.entries.get(&pair) else {
                    return Err(IntentGraphError::ReservationLedgerMismatch {
                        reservation: record.id,
                    });
                };
                let valid = companion.paired_with == Some(record.id)
                    && companion.owner_node == record.owner_node
                    && companion.state == record.state
                    && matches!(
                        (record.kind, companion.kind),
                        (
                            IntentNativeReservationKind::Constraint,
                            IntentNativeReservationKind::ConstraintSource
                        ) | (
                            IntentNativeReservationKind::ConstraintSource,
                            IntentNativeReservationKind::Constraint
                        ) | (
                            IntentNativeReservationKind::Dimension,
                            IntentNativeReservationKind::DimensionSource
                        ) | (
                            IntentNativeReservationKind::DimensionSource,
                            IntentNativeReservationKind::Dimension
                        )
                    );
                if !valid {
                    return Err(IntentGraphError::ReservationLedgerMismatch {
                        reservation: record.id,
                    });
                }
                let owner_first = match (record.kind, companion.kind) {
                    (
                        IntentNativeReservationKind::Constraint,
                        IntentNativeReservationKind::ConstraintSource,
                    )
                    | (
                        IntentNativeReservationKind::Dimension,
                        IntentNativeReservationKind::DimensionSource,
                    ) => record.id.raw().checked_add(1) == Some(companion.id.raw()),
                    (
                        IntentNativeReservationKind::ConstraintSource,
                        IntentNativeReservationKind::Constraint,
                    )
                    | (
                        IntentNativeReservationKind::DimensionSource,
                        IntentNativeReservationKind::Dimension,
                    ) => companion.id.raw().checked_add(1) == Some(record.id.raw()),
                    _ => false,
                };
                if !owner_first {
                    return Err(IntentGraphError::ReservationLedgerMismatch {
                        reservation: record.id,
                    });
                }
            }
        }
        Ok(())
    }
}

impl Default for IntentReservationLedger {
    fn default() -> Self {
        Self::empty()
    }
}

/// One stable typed schema-generated output.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct IntentPort {
    pub id: PortId,
    pub selector: IntentPortSelector,
    pub kind: IntentPortKind,
    pub flow: IntentIdentityFlow,
    pub writable: Vec<LeafField>,
}

impl IntentPort {
    #[must_use]
    pub const fn as_ref(&self, node: NodeId) -> IntentPortRef {
        IntentPortRef {
            node,
            port: self.id,
            kind: self.kind,
        }
    }
}

/// One stable variable-cardinality child and its generated ports.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct IntentChild {
    pub id: ChildId,
    pub schema: IntentChildSchema,
    pub ports: Vec<PortId>,
}

/// One closed typed declaration in the unordered graph.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct IntentNode {
    pub id: NodeId,
    pub symbol: crate::IntentKey,
    pub kind: IntentNodeKind,
    pub suppressed: bool,
    pub inputs: BTreeMap<crate::InputSlot, IntentPortRef>,
    pub fields: BTreeMap<IntentFieldKey, IntentLiteral>,
    /// Untrusted operation output shape authenticated against the existing
    /// Rust operation proposal before any reservation is consumed.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub operation_outputs: Vec<IntentOperationOutput>,
    pub ports: BTreeMap<PortId, IntentPort>,
    pub reservations: BTreeMap<ReservationId, IntentReservation>,
    pub child_order: Vec<ChildId>,
    pub children: BTreeMap<ChildId, IntentChild>,
}

impl IntentNode {
    #[must_use]
    pub fn port(&self, id: PortId) -> Option<&IntentPort> {
        self.ports.get(&id)
    }

    #[must_use]
    pub fn port_by_selector(&self, selector: IntentPortSelector) -> Option<&IntentPort> {
        self.ports.values().find(|port| port.selector == selector)
    }

    #[must_use]
    pub fn dependencies(&self) -> BTreeSet<NodeId> {
        self.inputs
            .values()
            .map(|source| source.node)
            .chain(self.ports.values().filter_map(|port| match port.flow {
                IntentIdentityFlow::OwnedLogical | IntentIdentityFlow::Created { .. } => None,
                IntentIdentityFlow::Aliased { source }
                | IntentIdentityFlow::Continued { source, .. }
                | IntentIdentityFlow::Retired { source, .. } => Some(source.node),
            }))
            .collect()
    }
}

/// Unordered canonical stable declaration graph.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct IntentGraph {
    pub(crate) revision: Revision,
    pub(crate) nodes: BTreeMap<NodeId, IntentNode>,
}

impl IntentGraph {
    #[must_use]
    pub fn empty() -> Self {
        Self {
            revision: Revision::from_raw(0),
            nodes: BTreeMap::new(),
        }
    }

    #[must_use]
    pub fn nodes(&self) -> &BTreeMap<NodeId, IntentNode> {
        &self.nodes
    }

    #[must_use]
    pub fn node(&self, id: NodeId) -> Option<&IntentNode> {
        self.nodes.get(&id)
    }

    /// Resolves one durable developer-facing symbol independently of display
    /// name and organization order.
    #[must_use]
    pub fn node_by_symbol(&self, symbol: &crate::IntentKey) -> Option<&IntentNode> {
        self.nodes.values().find(|node| &node.symbol == symbol)
    }

    #[must_use]
    pub fn port(&self, reference: IntentPortRef) -> Option<&IntentPort> {
        self.nodes
            .get(&reference.node)
            .and_then(|node| node.ports.get(&reference.port))
            .filter(|port| port.kind == reference.kind)
    }

    #[must_use]
    pub fn identity(&self) -> IntentGraphIdentity {
        IntentGraphIdentity(ComponentIdentity {
            revision: self.revision,
            digest: self.digest(),
        })
    }

    /// Computes the exact canonical graph content digest.
    ///
    /// # Panics
    ///
    /// Panics only if serialization of this closed in-memory schema fails,
    /// which its `Serialize` implementation cannot ordinarily do.
    #[must_use]
    pub fn digest(&self) -> ContentDigest {
        digest_bytes(
            &serde_json::to_vec(&(self.revision, &self.nodes))
                .expect("intent graph is infallibly serializable"),
        )
    }

    /// Returns the canonical stable dependency schedule. Presentation order is
    /// never consulted; stable IDs break every ready-set tie.
    ///
    /// # Errors
    ///
    /// Returns a structural error for an unknown dependency or dependency cycle.
    pub fn canonical_schedule(&self) -> Result<Vec<NodeId>, IntentGraphError> {
        canonical_schedule(&self.nodes)
    }

    /// Computes the exact transitive dependent closure, including each root.
    ///
    /// # Errors
    ///
    /// Returns [`IntentGraphError::UnknownNode`] when a root is absent.
    pub fn dependent_closure(
        &self,
        roots: impl IntoIterator<Item = NodeId>,
    ) -> Result<BTreeSet<NodeId>, IntentGraphError> {
        let roots = roots.into_iter().collect::<BTreeSet<_>>();
        for root in &roots {
            if !self.nodes.contains_key(root) {
                return Err(IntentGraphError::UnknownNode(*root));
            }
        }
        let mut reverse = BTreeMap::<NodeId, BTreeSet<NodeId>>::new();
        for (node, value) in &self.nodes {
            for dependency in value.dependencies() {
                reverse.entry(dependency).or_default().insert(*node);
            }
        }
        let mut closure = roots.clone();
        let mut pending = roots;
        while let Some(node) = pending.pop_first() {
            if let Some(dependents) = reverse.get(&node) {
                for dependent in dependents {
                    if closure.insert(*dependent) {
                        pending.insert(*dependent);
                    }
                }
            }
        }
        Ok(closure)
    }

    /// Validates all schema, reference, DAG, reservation, and identity-flow
    /// invariants without materializing geometry.
    ///
    /// # Errors
    ///
    /// Returns the first bounded structural, schema, lifecycle, or wire-value
    /// violation.
    #[allow(
        clippy::too_many_lines,
        reason = "one validation pass keeps cross-schema graph invariants auditable"
    )]
    pub fn validate(&self) -> Result<(), IntentGraphError> {
        if self.nodes.len() > MAX_INTENT_NODES {
            return Err(IntentGraphError::ResourceLimit {
                resource: "intent nodes",
                actual: self.nodes.len(),
                limit: MAX_INTENT_NODES,
            });
        }
        let mut ports = BTreeMap::<PortId, (NodeId, &IntentPort)>::new();
        let mut reservations = BTreeSet::new();
        let mut children = BTreeSet::new();
        let mut symbols = BTreeSet::new();
        for (id, node) in &self.nodes {
            if *id != node.id {
                return Err(IntentGraphError::MapKeyMismatch { kind: "node" });
            }
            if !symbols.insert(&node.symbol) {
                return Err(IntentGraphError::DuplicateSymbol(node.symbol.clone()));
            }
            if node.inputs.len() > MAX_INTENT_NODE_INPUTS {
                return Err(IntentGraphError::ResourceLimit {
                    resource: "node inputs",
                    actual: node.inputs.len(),
                    limit: MAX_INTENT_NODE_INPUTS,
                });
            }
            if node.fields.len() > MAX_INTENT_NODE_FIELDS {
                return Err(IntentGraphError::ResourceLimit {
                    resource: "node fields",
                    actual: node.fields.len(),
                    limit: MAX_INTENT_NODE_FIELDS,
                });
            }
            for value in node.fields.values() {
                value.validate()?;
            }
            validate_operation_outputs(*id, &node.kind, &node.operation_outputs)?;
            if let IntentNodeKind::Bootstrap { object } = &node.kind {
                object.validate()?;
            }
            let dynamic_children = u16::try_from(node.children.len())
                .map_err(|_| IntentGraphError::InvalidChildSchema { node: *id })?;
            validate_declaration_schema(
                *id,
                &node.kind,
                dynamic_children,
                &node.inputs,
                &node.fields,
            )?;
            for (slot, source) in &node.inputs {
                if !node.kind.accepts_input(slot.role) {
                    return Err(IntentGraphError::InputRoleNotAccepted {
                        node: *id,
                        role: slot.role,
                    });
                }
                if let Some(expected) = slot.role.expected_kind()
                    && expected != source.kind
                {
                    return Err(IntentGraphError::InputKindMismatch {
                        node: *id,
                        expected,
                        actual: source.kind,
                    });
                }
            }
            if node.child_order.len() != node.children.len()
                || node.child_order.iter().collect::<BTreeSet<_>>().len() != node.child_order.len()
            {
                return Err(IntentGraphError::InvalidChildOrder { node: *id });
            }
            for child in &node.child_order {
                let value = node
                    .children
                    .get(child)
                    .ok_or(IntentGraphError::InvalidChildOrder { node: *id })?;
                if value.id != *child || !children.insert(*child) {
                    return Err(IntentGraphError::DuplicateIdentity { kind: "child" });
                }
                if value.schema != node.kind.child_schema() {
                    return Err(IntentGraphError::InvalidChildSchema { node: *id });
                }
                for port in &value.ports {
                    if !node.ports.contains_key(port) {
                        return Err(IntentGraphError::UnknownChildPort {
                            node: *id,
                            port: *port,
                        });
                    }
                }
            }
            validate_schema_ports(node)?;
            for (port_id, port) in &node.ports {
                if *port_id != port.id || ports.insert(*port_id, (*id, port)).is_some() {
                    return Err(IntentGraphError::DuplicateIdentity { kind: "port" });
                }
                let mut writable = port.writable.clone();
                writable.sort_unstable();
                writable.dedup();
                if writable != port.writable {
                    return Err(IntentGraphError::InvalidWritableLeaves { node: *id });
                }
            }
            for (reservation_id, reservation) in &node.reservations {
                if *reservation_id != reservation.id || !reservations.insert(*reservation_id) {
                    return Err(IntentGraphError::DuplicateIdentity {
                        kind: "reservation",
                    });
                }
                if let Some(pair) = reservation.paired_with {
                    let Some(companion) = node.reservations.get(&pair) else {
                        return Err(IntentGraphError::UnknownReservation {
                            node: *id,
                            reservation: pair,
                        });
                    };
                    let valid_pair = companion.paired_with == Some(*reservation_id)
                        && matches!(
                            (reservation.kind, companion.kind),
                            (
                                IntentNativeReservationKind::Constraint,
                                IntentNativeReservationKind::ConstraintSource
                            ) | (
                                IntentNativeReservationKind::ConstraintSource,
                                IntentNativeReservationKind::Constraint
                            ) | (
                                IntentNativeReservationKind::Dimension,
                                IntentNativeReservationKind::DimensionSource
                            ) | (
                                IntentNativeReservationKind::DimensionSource,
                                IntentNativeReservationKind::Dimension
                            )
                        );
                    if !valid_pair {
                        return Err(IntentGraphError::InvalidReservationPair {
                            node: *id,
                            reservation: *reservation_id,
                        });
                    }
                } else if matches!(
                    reservation.kind,
                    IntentNativeReservationKind::Constraint
                        | IntentNativeReservationKind::ConstraintSource
                        | IntentNativeReservationKind::Dimension
                        | IntentNativeReservationKind::DimensionSource
                ) {
                    return Err(IntentGraphError::InvalidReservationPair {
                        node: *id,
                        reservation: *reservation_id,
                    });
                }
            }
        }

        for (node_id, node) in &self.nodes {
            for source in node.inputs.values() {
                validate_port_reference(*node_id, *source, &ports)?;
            }
            for port in node.ports.values() {
                match port.flow {
                    IntentIdentityFlow::OwnedLogical => {}
                    IntentIdentityFlow::Created { reservation } => {
                        let value = node.reservations.get(&reservation).ok_or(
                            IntentGraphError::UnknownReservation {
                                node: *node_id,
                                reservation,
                            },
                        )?;
                        if value.kind.port_kind() != port.kind {
                            return Err(IntentGraphError::ReservationKindMismatch {
                                node: *node_id,
                                port: port.id,
                            });
                        }
                    }
                    IntentIdentityFlow::Aliased { source }
                    | IntentIdentityFlow::Continued { source, .. }
                    | IntentIdentityFlow::Retired { source, .. } => {
                        validate_port_reference(*node_id, source, &ports)?;
                        if source.kind != port.kind {
                            return Err(IntentGraphError::IdentityKindMismatch {
                                node: *node_id,
                                expected: port.kind,
                                actual: source.kind,
                            });
                        }
                    }
                }
            }
        }

        let schedule = canonical_schedule(&self.nodes)?;
        validate_identity_flow(&schedule, &self.nodes)?;
        Ok(())
    }

    pub(crate) fn set_suppressed(
        &mut self,
        node: NodeId,
        suppressed: bool,
    ) -> Result<bool, IntentGraphError> {
        let value = self
            .nodes
            .get_mut(&node)
            .ok_or(IntentGraphError::UnknownNode(node))?;
        let changed = value.suppressed != suppressed;
        value.suppressed = suppressed;
        Ok(changed)
    }

    pub(crate) fn set_field(
        &mut self,
        node: NodeId,
        field: IntentFieldKey,
        value: IntentLiteral,
    ) -> Result<bool, IntentGraphError> {
        value.validate()?;
        let node = self
            .nodes
            .get_mut(&node)
            .ok_or(IntentGraphError::UnknownNode(node))?;
        if node.fields.get(&field) == Some(&value) {
            return Ok(false);
        }
        node.fields.insert(field, value);
        Ok(true)
    }

    pub(crate) fn rebind_input(
        &mut self,
        node: NodeId,
        slot: crate::InputSlot,
        source: IntentPortRef,
    ) -> Result<bool, IntentGraphError> {
        let target = self
            .nodes
            .get_mut(&node)
            .ok_or(IntentGraphError::UnknownNode(node))?;
        if !target.kind.accepts_input(slot.role) {
            return Err(IntentGraphError::InputRoleNotAccepted {
                node,
                role: slot.role,
            });
        }
        if let Some(expected) = slot.role.expected_kind()
            && expected != source.kind
        {
            return Err(IntentGraphError::InputKindMismatch {
                node,
                expected,
                actual: source.kind,
            });
        }
        let Some(previous) = target.inputs.get(&slot).copied() else {
            return Err(IntentGraphError::UnknownInputSlot { node, slot });
        };
        if previous == source {
            return Ok(false);
        }

        let dynamic_children = u16::try_from(target.children.len())
            .map_err(|_| IntentGraphError::InvalidPortSchema { node })?;
        let mut specs = node_port_specs(
            &target.kind,
            &target.fields,
            dynamic_children,
            &target.operation_outputs,
        );
        for (ordinal, child) in target.child_order.iter().enumerate() {
            let ordinal =
                u16::try_from(ordinal).map_err(|_| IntentGraphError::InvalidPortSchema { node })?;
            specs.extend(child_port_specs(
                &target.kind,
                target.children[child].schema,
                ordinal,
                dynamic_children,
                &target.fields,
            ));
        }
        for spec in specs
            .into_iter()
            .filter(|spec| spec.alias_input == Some(slot))
        {
            let port = target
                .ports
                .values_mut()
                .find(|port| port.selector == spec.selector)
                .ok_or(IntentGraphError::InvalidPortSchema { node })?;
            port.flow = IntentIdentityFlow::Aliased { source };
        }
        if let IntentNodeKind::Identity { transition, .. } = &target.kind {
            for port in target.ports.values_mut() {
                port.flow = match *transition {
                    crate::IdentityTransitionKind::Alias => IntentIdentityFlow::Aliased { source },
                    crate::IdentityTransitionKind::Continue => IntentIdentityFlow::Continued {
                        source,
                        generation: 0,
                    },
                    crate::IdentityTransitionKind::Retire => IntentIdentityFlow::Retired {
                        source,
                        generation: 0,
                    },
                };
            }
        }
        target.inputs.insert(slot, source);
        Ok(true)
    }

    pub(crate) fn remove_nodes(
        &mut self,
        nodes: &BTreeSet<NodeId>,
        instance: &mut IntentInstanceState,
    ) {
        for node in nodes {
            self.nodes.remove(node);
        }
        instance
            .values
            .retain(|leaf, _| !nodes.contains(&leaf.node));
    }

    pub(crate) fn writable_leaf(&self, leaf: LeafRef) -> Result<&IntentPort, IntentGraphError> {
        let node = self
            .nodes
            .get(&leaf.node)
            .ok_or(IntentGraphError::UnknownNode(leaf.node))?;
        let port = node
            .ports
            .get(&leaf.port)
            .ok_or(IntentGraphError::UnknownPort {
                node: leaf.node,
                port: leaf.port,
            })?;
        if !port.writable.contains(&leaf.field) {
            return Err(IntentGraphError::UnknownWritableLeaf { leaf });
        }
        Ok(port)
    }

    /// Strict deterministic canonical graph JSON.
    ///
    /// # Errors
    ///
    /// Returns a structural, resource-limit, or serialization error.
    pub fn to_canonical_json(&self) -> Result<String, IntentGraphError> {
        self.validate()?;
        let mut wire = IntentGraphWire {
            version: INTENT_GRAPH_VERSION,
            graph: self.clone(),
            digest: ContentDigest::zero(),
        };
        wire.digest = graph_wire_digest(&wire);
        let json = serde_json::to_string(&wire)?;
        if json.len() > MAX_INTENT_GRAPH_JSON_BYTES {
            return Err(IntentGraphError::JsonResourceLimit {
                limit: MAX_INTENT_GRAPH_JSON_BYTES,
            });
        }
        Ok(json)
    }

    /// Imports strict canonical graph JSON and authenticates its digest.
    ///
    /// # Errors
    ///
    /// Returns an error for excessive, malformed, non-canonical, unsupported,
    /// digest-mismatched, or structurally invalid input.
    pub fn from_json(json: &str) -> Result<Self, IntentGraphError> {
        if json.len() > MAX_INTENT_GRAPH_JSON_BYTES {
            return Err(IntentGraphError::JsonResourceLimit {
                limit: MAX_INTENT_GRAPH_JSON_BYTES,
            });
        }
        let wire: IntentGraphWire = serde_json::from_str(json)?;
        if wire.version != INTENT_GRAPH_VERSION {
            return Err(IntentGraphError::UnsupportedVersion {
                expected: INTENT_GRAPH_VERSION,
                actual: wire.version,
            });
        }
        if wire.digest != graph_wire_digest(&wire) {
            return Err(IntentGraphError::DigestMismatch);
        }
        if serde_json::to_string(&wire)? != json {
            return Err(IntentGraphError::NonCanonicalJson);
        }
        wire.graph.validate()?;
        Ok(wire.graph)
    }
}

impl Default for IntentGraph {
    fn default() -> Self {
        Self::empty()
    }
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct IntentGraphWire {
    version: u32,
    graph: IntentGraph,
    digest: ContentDigest,
}

fn graph_wire_digest(wire: &IntentGraphWire) -> ContentDigest {
    digest_bytes(
        &serde_json::to_vec(&(wire.version, &wire.graph))
            .expect("graph wire payload is infallibly serializable"),
    )
}

/// Structural validation or strict persistence failure.
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum IntentGraphError {
    #[error("unknown intent node {0}")]
    UnknownNode(NodeId),
    #[error("unknown port {port} on node {node}")]
    UnknownPort { node: NodeId, port: PortId },
    #[error("unknown schema port selector {selector:?} on node {node}")]
    UnknownPortSelector {
        node: NodeId,
        selector: IntentPortSelector,
    },
    #[error("unknown native reservation {reservation} on node {node}")]
    UnknownReservation {
        node: NodeId,
        reservation: ReservationId,
    },
    #[error("unknown child port {port} on node {node}")]
    UnknownChildPort { node: NodeId, port: PortId },
    #[error("unknown writable leaf {leaf:?}")]
    UnknownWritableLeaf { leaf: LeafRef },
    #[error("node {node} does not accept input role {role:?}")]
    InputRoleNotAccepted {
        node: NodeId,
        role: crate::InputRole,
    },
    #[error("node {node} is missing required input slot {slot:?}")]
    MissingRequiredInput { node: NodeId, slot: InputSlot },
    #[error("node {node} has unexpected input slot {slot:?}")]
    UnexpectedInputSlot { node: NodeId, slot: InputSlot },
    #[error("node {node} input choice requires {minimum}..={maximum} operands, got {actual}")]
    InputChoiceCardinality {
        node: NodeId,
        minimum: u16,
        maximum: u16,
        actual: usize,
    },
    #[error("unknown existing input slot {slot:?} on node {node}")]
    UnknownInputSlot {
        node: NodeId,
        slot: crate::InputSlot,
    },
    #[error("input kind mismatch on node {node}: expected {expected:?}, got {actual:?}")]
    InputKindMismatch {
        node: NodeId,
        expected: IntentPortKind,
        actual: IntentPortKind,
    },
    #[error("node {node} has unknown definition field `{field:?}`")]
    UnknownDefinitionField { node: NodeId, field: IntentFieldKey },
    #[error("node {node} is missing required definition field `{field:?}`")]
    MissingRequiredDefinitionField { node: NodeId, field: IntentFieldKey },
    #[error("node {node} definition field `{field:?}` does not match {expected:?}")]
    DefinitionFieldLiteralMismatch {
        node: NodeId,
        field: IntentFieldKey,
        expected: crate::IntentLiteralSchema,
    },
    #[error("node {node} child cardinality requires {minimum}..={maximum}, got {actual}")]
    ChildCardinality {
        node: NodeId,
        minimum: u16,
        maximum: u16,
        actual: u16,
    },
    #[error("identity kind mismatch on node {node}: expected {expected:?}, got {actual:?}")]
    IdentityKindMismatch {
        node: NodeId,
        expected: IntentPortKind,
        actual: IntentPortKind,
    },
    #[error("reservation kind does not match port {port} on node {node}")]
    ReservationKindMismatch { node: NodeId, port: PortId },
    #[error("reservation pair {reservation} on node {node} is invalid")]
    InvalidReservationPair {
        node: NodeId,
        reservation: ReservationId,
    },
    #[error("schema-generated ports do not match node {node}")]
    InvalidPortSchema { node: NodeId },
    #[error("reservation {reservation} on node {node} is not owned by a created port")]
    UnusedReservation {
        node: NodeId,
        reservation: ReservationId,
    },
    #[error("dependency cycle contains node {node}")]
    DependencyCycle { node: NodeId },
    #[error("identity generation forks at {port:?}")]
    IdentityFork { port: IntentPortRef },
    #[error("identity generation referenced from {node} was retired at {port:?}")]
    RetiredReference { node: NodeId, port: IntentPortRef },
    #[error("node {node} references superseded identity generation at {port:?}")]
    ConsumedReference { node: NodeId, port: IntentPortRef },
    #[error("invalid identity generation on node {node}: expected {expected}, got {actual}")]
    InvalidGeneration {
        node: NodeId,
        expected: u64,
        actual: u64,
    },
    #[error("identity {kind} is duplicated")]
    DuplicateIdentity { kind: &'static str },
    #[error("developer symbol `{0}` is duplicated")]
    DuplicateSymbol(crate::IntentKey),
    #[error("reservation ledger metadata mismatches reservation {reservation}")]
    ReservationLedgerMismatch { reservation: ReservationId },
    #[error(
        "historical reservation-ledger revision {historical} exceeds current revision {current}"
    )]
    ReservationLedgerRevisionRegression {
        historical: Revision,
        current: Revision,
    },
    #[error("invalid child ordering on node {node}")]
    InvalidChildOrder { node: NodeId },
    #[error("invalid child schema on node {node}")]
    InvalidChildSchema { node: NodeId },
    #[error("invalid writable leaves on node {node}")]
    InvalidWritableLeaves { node: NodeId },
    #[error("{kind} map key does not match stored identity")]
    MapKeyMismatch { kind: &'static str },
    #[error("{0} identity allocator exhausted")]
    IdExhausted(&'static str),
    #[error("intent resource limit exceeded for {resource}: {actual} > {limit}")]
    ResourceLimit {
        resource: &'static str,
        actual: usize,
        limit: usize,
    },
    #[error("intent graph JSON exceeds {limit} bytes")]
    JsonResourceLimit { limit: usize },
    #[error("unsupported intent graph version {actual}; expected {expected}")]
    UnsupportedVersion { expected: u32, actual: u32 },
    #[error("intent graph digest mismatch")]
    DigestMismatch,
    #[error("intent graph JSON is not canonical")]
    NonCanonicalJson,
    #[error(transparent)]
    Model(#[from] crate::model::IntentModelError),
    #[error(transparent)]
    Json(#[from] serde_json::Error),
}

#[derive(Clone, Debug)]
pub(crate) struct AllocatedDraft {
    pub id: NodeId,
    pub draft: IntentNodeDraft,
    pub ports: BTreeMap<PortId, AllocatedPort>,
    pub reservations: BTreeMap<ReservationId, IntentReservation>,
    pub child_order: Vec<ChildId>,
    pub children: BTreeMap<ChildId, IntentChild>,
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct AllocatedPort {
    pub id: PortId,
    pub spec: PortSpec,
    pub reservation: Option<ReservationId>,
}

#[allow(
    clippy::too_many_lines,
    reason = "one staging boundary validates and allocates the complete generated declaration"
)]
pub(crate) fn allocate_draft(
    draft: IntentNodeDraft,
    allocator: &mut IntentAllocatorHighWater,
) -> Result<AllocatedDraft, IntentGraphError> {
    if !checked_child_count(draft.dynamic_children) {
        return Err(IntentGraphError::ResourceLimit {
            resource: "node children",
            actual: usize::from(draft.dynamic_children),
            limit: crate::model::MAX_INTENT_NODE_CHILDREN,
        });
    }
    if draft.kind.child_schema() == IntentChildSchema::None && draft.dynamic_children != 0 {
        return Err(IntentGraphError::InvalidChildSchema {
            node: allocator.next_node,
        });
    }
    if draft.inputs.len() > MAX_INTENT_NODE_INPUTS {
        return Err(IntentGraphError::ResourceLimit {
            resource: "node inputs",
            actual: draft.inputs.len(),
            limit: MAX_INTENT_NODE_INPUTS,
        });
    }
    if draft.fields.len() > MAX_INTENT_NODE_FIELDS {
        return Err(IntentGraphError::ResourceLimit {
            resource: "node fields",
            actual: draft.fields.len(),
            limit: MAX_INTENT_NODE_FIELDS,
        });
    }
    for (slot, source) in &draft.inputs {
        if !draft.kind.accepts_input(slot.role) {
            return Err(IntentGraphError::InputRoleNotAccepted {
                node: allocator.next_node,
                role: slot.role,
            });
        }
        if let PatchPortRef::Stable { port } = source
            && let Some(expected) = slot.role.expected_kind()
            && expected != port.kind
        {
            return Err(IntentGraphError::InputKindMismatch {
                node: allocator.next_node,
                expected,
                actual: port.kind,
            });
        }
    }
    for value in draft.fields.values() {
        value.validate()?;
    }
    validate_operation_outputs(allocator.next_node, &draft.kind, &draft.operation_outputs)?;
    if let IntentNodeKind::Bootstrap { object } = &draft.kind {
        object.validate()?;
    }
    validate_declaration_schema(
        allocator.next_node,
        &draft.kind,
        draft.dynamic_children,
        &draft.inputs,
        &draft.fields,
    )?;
    for values in draft.initial_instance.values() {
        for value in values.values() {
            value.validate()?;
        }
    }

    let id = allocator.allocate_node()?;
    let mut ports = BTreeMap::new();
    let mut reservations = BTreeMap::new();
    for spec in node_port_specs(
        &draft.kind,
        &draft.fields,
        draft.dynamic_children,
        &draft.operation_outputs,
    ) {
        let reserve = spec.native.is_some()
            && !spec
                .alias_input
                .is_some_and(|slot| draft.inputs.contains_key(&slot));
        allocate_port_spec(id, spec, reserve, allocator, &mut ports, &mut reservations)?;
    }
    let mut child_order = Vec::new();
    let mut children = BTreeMap::new();
    for ordinal in 0..draft.dynamic_children {
        let child_id = allocator.allocate_child()?;
        let mut child_ports = Vec::new();
        for spec in child_port_specs(
            &draft.kind,
            draft.kind.child_schema(),
            ordinal,
            draft.dynamic_children,
            &draft.fields,
        ) {
            let reserve = spec.native.is_some()
                && !spec
                    .alias_input
                    .is_some_and(|slot| draft.inputs.contains_key(&slot));
            let port =
                allocate_port_spec(id, spec, reserve, allocator, &mut ports, &mut reservations)?;
            child_ports.push(port);
        }
        child_order.push(child_id);
        children.insert(
            child_id,
            IntentChild {
                id: child_id,
                schema: draft.kind.child_schema(),
                ports: child_ports,
            },
        );
    }
    pair_native_reservations(id, &ports, &mut reservations)?;
    Ok(AllocatedDraft {
        id,
        draft,
        ports,
        reservations,
        child_order,
        children,
    })
}

fn validate_declaration_schema<T>(
    node: NodeId,
    kind: &IntentNodeKind,
    dynamic_children: u16,
    inputs: &BTreeMap<InputSlot, T>,
    fields: &BTreeMap<IntentFieldKey, IntentLiteral>,
) -> Result<(), IntentGraphError> {
    // Normalized bootstrap object payloads are decoded by their exact host
    // codec. The intent graph still owns their closed roles, catalog
    // dependency, field-free envelope, and bounded object payload.
    if matches!(
        kind,
        IntentNodeKind::Bootstrap {
            object: crate::IntentBootstrapObject {
                kind: BootstrapNativeKind::SemanticSource,
                ..
            }
        }
    ) {
        let slot = InputSlot::new(InputRole::Catalog, 0);
        if !inputs.contains_key(&slot) {
            return Err(IntentGraphError::MissingRequiredInput { node, slot });
        }
    }

    let schema = kind.schema(dynamic_children);
    if dynamic_children < schema.minimum_children || dynamic_children > schema.maximum_children {
        return Err(IntentGraphError::ChildCardinality {
            node,
            minimum: schema.minimum_children,
            maximum: schema.maximum_children,
            actual: dynamic_children,
        });
    }
    if !matches!(kind, IntentNodeKind::Bootstrap { .. }) {
        validate_declaration_inputs(node, kind, &schema, inputs)?;
    }

    for (key, value) in fields {
        let Some(field) = schema.field(key) else {
            return Err(IntentGraphError::UnknownDefinitionField {
                node,
                field: key.clone(),
            });
        };
        if !field.literal.accepts(value) {
            return Err(IntentGraphError::DefinitionFieldLiteralMismatch {
                node,
                field: key.clone(),
                expected: field.literal,
            });
        }
    }
    for field in schema.fields.iter().filter(|field| field.required) {
        if !fields.contains_key(&field.field) {
            return Err(IntentGraphError::MissingRequiredDefinitionField {
                node,
                field: field.field.clone(),
            });
        }
    }
    Ok(())
}

fn validate_operation_outputs(
    node: NodeId,
    kind: &IntentNodeKind,
    outputs: &[IntentOperationOutput],
) -> Result<(), IntentGraphError> {
    let IntentNodeKind::Operation { operation } = kind else {
        if outputs.is_empty() {
            return Ok(());
        }
        return Err(IntentGraphError::InvalidPortSchema { node });
    };
    if outputs.len() > MAX_INTENT_OPERATION_OUTPUTS {
        return Err(IntentGraphError::ResourceLimit {
            resource: "operation outputs",
            actual: outputs.len(),
            limit: MAX_INTENT_OPERATION_OUTPUTS,
        });
    }
    if matches!(
        operation,
        crate::OperationKind::Split
            | crate::OperationKind::Break
            | crate::OperationKind::Trim
            | crate::OperationKind::Extend
    ) && !outputs.is_empty()
    {
        return Err(IntentGraphError::InvalidPortSchema { node });
    }
    let mut spans = 0_usize;
    for output in outputs {
        match output.kind {
            IntentOperationOutputKind::Curve if output.curve_span_count == 0 => {
                return Err(IntentGraphError::InvalidPortSchema { node });
            }
            IntentOperationOutputKind::Curve => {
                spans = spans
                    .checked_add(usize::from(output.curve_span_count))
                    .ok_or(IntentGraphError::InvalidPortSchema { node })?;
            }
            _ if output.curve_span_count != 0 => {
                return Err(IntentGraphError::InvalidPortSchema { node });
            }
            _ => {}
        }
    }
    if spans > usize::from(u16::MAX) {
        return Err(IntentGraphError::ResourceLimit {
            resource: "operation curve spans",
            actual: spans,
            limit: usize::from(u16::MAX),
        });
    }
    Ok(())
}

fn validate_declaration_inputs<T>(
    node: NodeId,
    kind: &IntentNodeKind,
    schema: &crate::IntentNodeSchema,
    inputs: &BTreeMap<InputSlot, T>,
) -> Result<(), IntentGraphError> {
    for slot in inputs.keys() {
        let Some(cardinality) = schema.input(slot.role) else {
            return Err(IntentGraphError::UnexpectedInputSlot { node, slot: *slot });
        };
        if slot.index >= cardinality.maximum {
            return Err(IntentGraphError::UnexpectedInputSlot { node, slot: *slot });
        }
    }
    for cardinality in &schema.inputs {
        let actual = inputs
            .keys()
            .filter(|slot| slot.role == cardinality.role)
            .count();
        let actual = u16::try_from(actual).map_err(|_| IntentGraphError::ResourceLimit {
            resource: "node input role cardinality",
            actual,
            limit: usize::from(u16::MAX),
        })?;
        if actual < cardinality.minimum {
            return Err(IntentGraphError::MissingRequiredInput {
                node,
                slot: InputSlot::new(cardinality.role, actual),
            });
        }
        if actual > cardinality.maximum {
            return Err(IntentGraphError::UnexpectedInputSlot {
                node,
                slot: InputSlot::new(cardinality.role, cardinality.maximum),
            });
        }
        // Geometry recipes retain the semantic authored-point slot on each
        // output port. Any subset may alias pre-existing points while the
        // remaining slots allocate new native points, so those optional
        // aliases are intentionally sparse. Exact relation, dimension,
        // aggregate and operation operand lists remain contiguous.
        let sparse_geometry_points =
            matches!(kind, IntentNodeKind::Geometry { .. }) && cardinality.role == InputRole::Point;
        if !sparse_geometry_points {
            for index in 0..actual {
                let slot = InputSlot::new(cardinality.role, index);
                if !inputs.contains_key(&slot) {
                    return Err(IntentGraphError::MissingRequiredInput { node, slot });
                }
            }
        }
    }
    for choice in &schema.input_choices {
        let actual = choice
            .alternatives
            .iter()
            .filter(|slot| inputs.contains_key(slot))
            .count();
        if actual < usize::from(choice.minimum) || actual > usize::from(choice.maximum) {
            return Err(IntentGraphError::InputChoiceCardinality {
                node,
                minimum: choice.minimum,
                maximum: choice.maximum,
                actual,
            });
        }
    }
    Ok(())
}

fn allocate_port_spec(
    node: NodeId,
    spec: PortSpec,
    reserve: bool,
    allocator: &mut IntentAllocatorHighWater,
    ports: &mut BTreeMap<PortId, AllocatedPort>,
    reservations: &mut BTreeMap<ReservationId, IntentReservation>,
) -> Result<PortId, IntentGraphError> {
    let id = allocator.allocate_port()?;
    let reservation = if reserve {
        let value = allocator.allocate_reservation()?;
        let kind = spec
            .native
            .ok_or(IntentGraphError::InvalidPortSchema { node })?;
        reservations.insert(
            value,
            IntentReservation {
                id: value,
                kind,
                paired_with: None,
            },
        );
        Some(value)
    } else {
        None
    };
    ports.insert(
        id,
        AllocatedPort {
            id,
            spec,
            reservation,
        },
    );
    Ok(id)
}

fn pair_native_reservations(
    node: NodeId,
    ports: &BTreeMap<PortId, AllocatedPort>,
    reservations: &mut BTreeMap<ReservationId, IntentReservation>,
) -> Result<(), IntentGraphError> {
    for (owner, source) in [
        (
            IntentNativeReservationKind::Constraint,
            IntentNativeReservationKind::ConstraintSource,
        ),
        (
            IntentNativeReservationKind::Dimension,
            IntentNativeReservationKind::DimensionSource,
        ),
    ] {
        let reservations_for = |kind| {
            ports
                .values()
                .filter(|port| port.spec.native == Some(kind))
                .filter_map(|port| port.reservation)
                .collect::<Vec<_>>()
        };
        let owners = reservations_for(owner);
        let sources = reservations_for(source);
        if owners.len() != sources.len() {
            let reservation = owners
                .first()
                .or_else(|| sources.first())
                .copied()
                .ok_or(IntentGraphError::InvalidPortSchema { node })?;
            return Err(IntentGraphError::InvalidReservationPair { node, reservation });
        }
        for (owner_id, source_id) in owners.into_iter().zip(sources) {
            if source_id.raw() != owner_id.raw().checked_add(1).unwrap_or_default() {
                return Err(IntentGraphError::InvalidReservationPair {
                    node,
                    reservation: owner_id,
                });
            }
            reservations
                .get_mut(&owner_id)
                .expect("allocated owner reservation")
                .paired_with = Some(source_id);
            reservations
                .get_mut(&source_id)
                .expect("allocated source reservation")
                .paired_with = Some(owner_id);
        }
    }
    Ok(())
}

pub(crate) fn allocated_alias_ports(
    draft: &AllocatedDraft,
) -> BTreeMap<IntentPortSelector, IntentPortRef> {
    draft
        .ports
        .values()
        .map(|port| {
            (
                port.spec.selector,
                IntentPortRef {
                    node: draft.id,
                    port: port.id,
                    kind: port.spec.kind,
                },
            )
        })
        .collect()
}

#[allow(
    clippy::too_many_lines,
    reason = "draft completion atomically binds generated ports, identity flow, and instance leaves"
)]
pub(crate) fn finish_allocated_draft(
    allocated: AllocatedDraft,
    inputs: BTreeMap<crate::InputSlot, IntentPortRef>,
    instance: &mut IntentInstanceState,
) -> Result<IntentNode, IntentGraphError> {
    let identity_source = inputs
        .get(&crate::InputSlot::new(crate::InputRole::Identity, 0))
        .copied();
    let ports = allocated
        .ports
        .into_iter()
        .map(|(id, port)| {
            let flow = match &allocated.draft.kind {
                IntentNodeKind::Identity {
                    transition,
                    port_kind,
                } => {
                    let source = identity_source.ok_or(IntentGraphError::InputRoleNotAccepted {
                        node: allocated.id,
                        role: crate::InputRole::Identity,
                    })?;
                    if source.kind != *port_kind {
                        return Err(IntentGraphError::IdentityKindMismatch {
                            node: allocated.id,
                            expected: *port_kind,
                            actual: source.kind,
                        });
                    }
                    match transition {
                        crate::IdentityTransitionKind::Alias => {
                            IntentIdentityFlow::Aliased { source }
                        }
                        crate::IdentityTransitionKind::Continue => IntentIdentityFlow::Continued {
                            source,
                            generation: 0,
                        },
                        crate::IdentityTransitionKind::Retire => IntentIdentityFlow::Retired {
                            source,
                            generation: 0,
                        },
                    }
                }
                _ => match port.spec.alias_input.and_then(|slot| inputs.get(&slot)) {
                    Some(source) => IntentIdentityFlow::Aliased { source: *source },
                    None => port
                        .reservation
                        .map_or(IntentIdentityFlow::OwnedLogical, |reservation| {
                            IntentIdentityFlow::Created { reservation }
                        }),
                },
            };
            let writable = if matches!(flow, IntentIdentityFlow::Aliased { .. }) {
                Vec::new()
            } else {
                port.spec.writable.to_vec()
            };
            Ok((
                id,
                IntentPort {
                    id,
                    selector: port.spec.selector,
                    kind: port.spec.kind,
                    flow,
                    writable,
                },
            ))
        })
        .collect::<Result<BTreeMap<_, _>, IntentGraphError>>()?;

    for (selector, values) in &allocated.draft.initial_instance {
        let port = ports
            .values()
            .find(|port| port.selector == *selector)
            .ok_or(IntentGraphError::UnknownPortSelector {
                node: allocated.id,
                selector: *selector,
            })?;
        for (field, value) in values {
            if !port.writable.contains(field) || !literal_matches_leaf(value, *field) {
                return Err(IntentGraphError::UnknownWritableLeaf {
                    leaf: LeafRef {
                        node: allocated.id,
                        port: port.id,
                        field: *field,
                    },
                });
            }
            instance.values.insert(
                LeafRef {
                    node: allocated.id,
                    port: port.id,
                    field: *field,
                },
                value.clone(),
            );
        }
    }

    Ok(IntentNode {
        id: allocated.id,
        symbol: allocated.draft.symbol,
        kind: allocated.draft.kind,
        suppressed: allocated.draft.suppressed,
        inputs,
        fields: allocated.draft.fields,
        operation_outputs: allocated.draft.operation_outputs,
        ports,
        reservations: allocated.reservations,
        child_order: allocated.child_order,
        children: allocated.children,
    })
}

pub(crate) fn assign_identity_generations(graph: &mut IntentGraph) -> Result<(), IntentGraphError> {
    let schedule = graph.canonical_schedule()?;
    let mut generation = BTreeMap::<PortId, u64>::new();
    let mut token = BTreeMap::<PortId, PortId>::new();
    let mut current = BTreeMap::<PortId, u64>::new();
    for node_id in schedule {
        let port_ids = graph.nodes[&node_id]
            .ports
            .keys()
            .copied()
            .collect::<Vec<_>>();
        for port_id in port_ids {
            let flow = graph.nodes[&node_id].ports[&port_id].flow;
            match flow {
                IntentIdentityFlow::OwnedLogical | IntentIdentityFlow::Created { .. } => {
                    token.insert(port_id, port_id);
                    generation.insert(port_id, 0);
                    current.insert(port_id, 0);
                }
                IntentIdentityFlow::Aliased { source } => {
                    let root = token[&source.port];
                    if current[&root] != generation[&source.port] {
                        return Err(IntentGraphError::IdentityFork { port: source });
                    }
                    token.insert(port_id, root);
                    generation.insert(port_id, generation[&source.port]);
                }
                IntentIdentityFlow::Continued { source, .. }
                | IntentIdentityFlow::Retired { source, .. } => {
                    let root = token[&source.port];
                    let source_generation = generation[&source.port];
                    let expected = current[&root];
                    if source_generation != expected {
                        return Err(IntentGraphError::IdentityFork { port: source });
                    }
                    let next = expected
                        .checked_add(1)
                        .ok_or(IntentGraphError::IdExhausted("identity generation"))?;
                    token.insert(port_id, root);
                    generation.insert(port_id, next);
                    current.insert(root, next);
                    let port = graph
                        .nodes
                        .get_mut(&node_id)
                        .unwrap()
                        .ports
                        .get_mut(&port_id)
                        .unwrap();
                    port.flow = match flow {
                        IntentIdentityFlow::Continued { source, .. } => {
                            IntentIdentityFlow::Continued {
                                source,
                                generation: next,
                            }
                        }
                        IntentIdentityFlow::Retired { source, .. } => IntentIdentityFlow::Retired {
                            source,
                            generation: next,
                        },
                        _ => unreachable!(),
                    };
                }
            }
        }
    }
    Ok(())
}

#[allow(
    clippy::single_match_else,
    clippy::too_many_lines,
    reason = "one closed audit keeps generated ports, aliases, reservations, and the identity-node exception aligned"
)]
fn validate_schema_ports(node: &IntentNode) -> Result<(), IntentGraphError> {
    let dynamic_children = u16::try_from(node.children.len())
        .map_err(|_| IntentGraphError::InvalidPortSchema { node: node.id })?;
    let mut specs = node_port_specs(
        &node.kind,
        &node.fields,
        dynamic_children,
        &node.operation_outputs,
    );
    for (ordinal, child) in node.child_order.iter().enumerate() {
        let ordinal = u16::try_from(ordinal)
            .map_err(|_| IntentGraphError::InvalidPortSchema { node: node.id })?;
        let value = &node.children[child];
        specs.extend(child_port_specs(
            &node.kind,
            value.schema,
            ordinal,
            dynamic_children,
            &node.fields,
        ));
    }
    if specs.len() != node.ports.len() {
        return Err(IntentGraphError::InvalidPortSchema { node: node.id });
    }

    let mut used_reservations = BTreeSet::new();
    for spec in specs {
        let port = node
            .ports
            .values()
            .find(|port| port.selector == spec.selector)
            .ok_or(IntentGraphError::InvalidPortSchema { node: node.id })?;
        if port.kind != spec.kind {
            return Err(IntentGraphError::InvalidPortSchema { node: node.id });
        }
        match &node.kind {
            IntentNodeKind::Identity {
                transition,
                port_kind,
            } => {
                let source = node
                    .inputs
                    .get(&crate::InputSlot::new(crate::InputRole::Identity, 0))
                    .copied()
                    .ok_or(IntentGraphError::InvalidPortSchema { node: node.id })?;
                if *port_kind != port.kind
                    || !matches!(
                        (transition, port.flow),
                        (
                            crate::IdentityTransitionKind::Alias,
                            IntentIdentityFlow::Aliased { source: actual }
                        ) if actual == source
                    ) && !matches!(
                        (transition, port.flow),
                        (
                            crate::IdentityTransitionKind::Continue,
                            IntentIdentityFlow::Continued { source: actual, .. }
                        ) if actual == source
                    ) && !matches!(
                        (transition, port.flow),
                        (
                            crate::IdentityTransitionKind::Retire,
                            IntentIdentityFlow::Retired { source: actual, .. }
                        ) if actual == source
                    )
                    || !port.writable.is_empty()
                {
                    return Err(IntentGraphError::InvalidPortSchema { node: node.id });
                }
            }
            _ => {
                let alias_source = spec.alias_input.and_then(|slot| node.inputs.get(&slot));
                if let Some(source) = alias_source {
                    if port.flow != (IntentIdentityFlow::Aliased { source: *source })
                        || !port.writable.is_empty()
                    {
                        return Err(IntentGraphError::InvalidPortSchema { node: node.id });
                    }
                } else if let Some(native) = spec.native {
                    let IntentIdentityFlow::Created { reservation } = port.flow else {
                        return Err(IntentGraphError::InvalidPortSchema { node: node.id });
                    };
                    if node.reservations.get(&reservation).map(|value| value.kind) != Some(native) {
                        return Err(IntentGraphError::ReservationKindMismatch {
                            node: node.id,
                            port: port.id,
                        });
                    }
                    used_reservations.insert(reservation);
                    if port.writable != spec.writable {
                        return Err(IntentGraphError::InvalidPortSchema { node: node.id });
                    }
                } else if port.flow != IntentIdentityFlow::OwnedLogical
                    || port.writable != spec.writable
                {
                    return Err(IntentGraphError::InvalidPortSchema { node: node.id });
                }
            }
        }
    }
    if let Some(reservation) = node
        .reservations
        .keys()
        .find(|reservation| !used_reservations.contains(reservation))
    {
        return Err(IntentGraphError::UnusedReservation {
            node: node.id,
            reservation: *reservation,
        });
    }
    Ok(())
}

fn validate_port_reference(
    node: NodeId,
    source: IntentPortRef,
    ports: &BTreeMap<PortId, (NodeId, &IntentPort)>,
) -> Result<(), IntentGraphError> {
    let Some((owner, port)) = ports.get(&source.port) else {
        return Err(IntentGraphError::UnknownPort {
            node: source.node,
            port: source.port,
        });
    };
    if *owner != source.node {
        return Err(IntentGraphError::UnknownPort {
            node: source.node,
            port: source.port,
        });
    }
    if port.kind != source.kind {
        return Err(IntentGraphError::InputKindMismatch {
            node,
            expected: port.kind,
            actual: source.kind,
        });
    }
    Ok(())
}

fn canonical_schedule(
    nodes: &BTreeMap<NodeId, IntentNode>,
) -> Result<Vec<NodeId>, IntentGraphError> {
    let mut remaining = BTreeMap::<NodeId, usize>::new();
    let mut dependents = BTreeMap::<NodeId, BTreeSet<NodeId>>::new();
    for (node_id, node) in nodes {
        let dependencies = node.dependencies();
        for dependency in &dependencies {
            if !nodes.contains_key(dependency) {
                return Err(IntentGraphError::UnknownNode(*dependency));
            }
            dependents.entry(*dependency).or_default().insert(*node_id);
        }
        remaining.insert(*node_id, dependencies.len());
    }
    let mut ready = remaining
        .iter()
        .filter_map(|(node, count)| (*count == 0).then_some(*node))
        .collect::<BTreeSet<_>>();
    let mut schedule = Vec::with_capacity(nodes.len());
    while let Some(node) = ready.pop_first() {
        schedule.push(node);
        if let Some(values) = dependents.get(&node) {
            for dependent in values {
                let count = remaining
                    .get_mut(dependent)
                    .expect("every dependent is retained");
                *count -= 1;
                if *count == 0 {
                    ready.insert(*dependent);
                }
            }
        }
    }
    if schedule.len() != nodes.len() {
        let node = remaining
            .into_iter()
            .find_map(|(node, count)| (count != 0).then_some(node))
            .expect("a dependency cycle contains a node");
        return Err(IntentGraphError::DependencyCycle { node });
    }
    Ok(schedule)
}

#[derive(Clone, Copy)]
struct PortToken {
    root: PortId,
    generation: u64,
}

#[derive(Clone, Copy)]
struct TokenState {
    generation: u64,
    retired: bool,
}

#[allow(
    clippy::too_many_lines,
    reason = "one ordered pass plus final audit makes identity consumption and retirement explicit"
)]
fn validate_identity_flow(
    schedule: &[NodeId],
    nodes: &BTreeMap<NodeId, IntentNode>,
) -> Result<(), IntentGraphError> {
    let mut ports = BTreeMap::<PortId, PortToken>::new();
    let mut tokens = BTreeMap::<PortId, TokenState>::new();
    for node_id in schedule {
        for source in nodes[node_id].inputs.values() {
            let state = ports[&source.port];
            let token = tokens[&state.root];
            if token.retired {
                return Err(IntentGraphError::RetiredReference {
                    node: *node_id,
                    port: *source,
                });
            }
            if token.generation != state.generation {
                return Err(IntentGraphError::ConsumedReference {
                    node: *node_id,
                    port: *source,
                });
            }
        }
        for port in nodes[node_id].ports.values() {
            match port.flow {
                IntentIdentityFlow::OwnedLogical | IntentIdentityFlow::Created { .. } => {
                    ports.insert(
                        port.id,
                        PortToken {
                            root: port.id,
                            generation: 0,
                        },
                    );
                    tokens.insert(
                        port.id,
                        TokenState {
                            generation: 0,
                            retired: false,
                        },
                    );
                }
                IntentIdentityFlow::Aliased { source } => {
                    let state = ports[&source.port];
                    let token = tokens[&state.root];
                    if token.retired {
                        return Err(IntentGraphError::RetiredReference {
                            node: *node_id,
                            port: source,
                        });
                    }
                    if token.generation != state.generation {
                        return Err(IntentGraphError::IdentityFork { port: source });
                    }
                    ports.insert(port.id, state);
                }
                IntentIdentityFlow::Continued { source, generation }
                | IntentIdentityFlow::Retired { source, generation } => {
                    let source_state = ports[&source.port];
                    let token = tokens.get_mut(&source_state.root).unwrap();
                    if token.retired || token.generation != source_state.generation {
                        return Err(IntentGraphError::IdentityFork { port: source });
                    }
                    let expected = token
                        .generation
                        .checked_add(1)
                        .ok_or(IntentGraphError::IdExhausted("identity generation"))?;
                    if generation != expected {
                        return Err(IntentGraphError::InvalidGeneration {
                            node: *node_id,
                            expected,
                            actual: generation,
                        });
                    }
                    token.generation = generation;
                    token.retired = matches!(port.flow, IntentIdentityFlow::Retired { .. });
                    ports.insert(
                        port.id,
                        PortToken {
                            root: source_state.root,
                            generation,
                        },
                    );
                }
            }
        }
    }
    for (node_id, node) in nodes {
        for (slot, source) in &node.inputs {
            if matches!(node.kind, IntentNodeKind::Identity { .. })
                && slot.role == crate::InputRole::Identity
            {
                continue;
            }
            let state = ports[&source.port];
            let token = tokens[&state.root];
            if token.retired {
                return Err(IntentGraphError::RetiredReference {
                    node: *node_id,
                    port: *source,
                });
            }
            if token.generation != state.generation {
                return Err(IntentGraphError::ConsumedReference {
                    node: *node_id,
                    port: *source,
                });
            }
        }
    }
    Ok(())
}
